services:
  default:
    image: "aisiuk/inspect-tool-support"
    command: >
      sh -c "apt-get update && pip install biopython && echo 'E4_FASTA_Length_Statistics environment ready' && tail -f /dev/null"
    init: true
    network_mode: bridge # Enables internet access
    dns:
      - 8.8.8.8 # Google DNS
      - 1.1.1.1 # Cloudflare DNS
    dns_opt:
      - ndots:2
      - edns0
    stop_grace_period: 1s
    volumes:
      - ./data/uniprot_files:/app/data/uniprot_files
