services:
  default:
    image: "aisiuk/inspect-tool-support"
    command: >
        sh -c "echo 'H2_Allosteric_Network_Analysis environment ready' && tail -f /dev/null"
    init: true
    network_mode: bridge  # Enables internet access
    dns:
      - 8.8.8.8        # Google DNS
      - 1.1.1.1        # Cloudflare DNS
    dns_opt:
      - ndots:2
      - edns0
    stop_grace_period: 1s
    volumes:
    - ./data/H2_Allosteric_Network_Analysis:/app/task
    - ./data/pdb_files:/app/data/pdb_files