services:
  default:
    platform: "linux/amd64"
    image: "aisiuk/inspect-tool-support"
    command: >
      sh -c "set -e; \
      apt-get update; \
      apt-get install -y libnetcdf-dev; \
      git clone https://github.com/Discngine/fpocket.git; \
      cd fpocket; \
      make; \
      make install; \
      echo 'H8_Druggability_Assessment environment ready'; \
      pip install biopython numpy; \
      fpocket -v; \
      tail -f /dev/null"
    init: true
    network_mode: bridge # Enables internet access
    dns:
      - 8.8.8.8 # Google DNS
      - 1.1.1.1 # Cloudflare DNS
    dns_opt:
      - ndots:2
      - edns0
    stop_grace_period: 1s
    volumes:
      - ../data/pdb_files:/app/data/
