services:
  default:
    image: "aisiuk/inspect-tool-support"
    command: >
        sh -c "
        apt-get update && 
        apt-get install -y mafft dssp fpocket || echo 'Some apt packages may not be available' && 
        pip install biopython requests pandas numpy argparse ||  echo 'Some pip packages may have failed' &&
        echo 'Protein analysis environment ready' &&
        mafft --version &&
        fpocket -v || echo 'fpocket not available' &&
        python3 -c 'import Bio; print(\"BioPython available\")' || echo 'BioPython import test failed' &&
        python3 -c 'import requests; print(\"Requests available\")' || echo 'Requests import test failed' &&
        python3 -c 'import pandas; print(\"Pandas available\")' || echo 'Pandas import test failed' &&
        tail -f /dev/null"
    init: true
    network_mode: bridge  # Enables internet access
    dns:
      - 8.8.8.8        # Google DNS
      - 1.1.1.1        # Cloudflare DNS
    dns_opt:
      - ndots:2
      - edns0
    stop_grace_period: 1s
    volumes:
      - ./data:/app/data
      - ./:/app/workspace