services:
  default:
    image: "aisiuk/inspect-tool-support"
    command: >
        sh -c "
        apt-get update && 
        apt-get install -y mafft && 
        echo 'MAFFT installed successfully' &&
        mafft --version &&
        tail -f /dev/null"
    init: true
    network_mode: bridge  # Enables internet access
    dns:
      - 8.8.8.8        # Google DNS
      - 1.1.1.1        # Cloudflare DNS
    dns_opt:
      - ndots:2
      - edns0
    stop_grace_period: 1s
    volumes:
    - ./alpha_amylase_round0.csv:/app/alpha_amylase_round0.csv